name: 'Continuous Delivery (CD) Pipeline 🚀'

on: 
  workflow_dispatch:         # Enables you to be able to run this manually
                             # You can also specify which branch you'd want to run
                             # the workflow on in the Github UI
                             
  push:                      # Do not want to deploy on feature branches only want to
                             # Deploy on main branches hence what's specified against push 
    branches: 
    - main
    paths-ignore:           # Define what paths to ignore, ie things that have no impact on 
    - 'README.md'           # what the outputs of the respository such as Apps might be
    - 'Python_Cheat_Sheet.md'

concurrency:                # Cancel running jobs and prefer latest code
  group: ${{github.workflow}}-${{github.ref}} # Only care about the latest build against code being pushed
                            # github.workflow = The ref path to the workflow
                            #github. ref = The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by push, this is the branch or tag ref that was pushed.
  cancel-in-progress: true  # means github will cancel any in progress workflow against this one when new code is pushed to main

jobs: 
  CIPipeline: 
    uses: ./.github/workflows/CIPipeline.yaml
    