@startuml Cabin_Moods_Application_Start_Up_UC Sequence
    
autonumber

actor "User" as U  
participant "Client App" as CA 
control "Scenario Service" as SS
database "Scenario Service Settings Config" as SSSC
participant "Settings Management Client" as SMC
participant "Vehicle Lifecycle - VIP" as VIP
title Scenario Service Start Up Behaviour with Settings Management Client

== Client Request for Settings Names == 

'all scenarios is_shareable flag = false
'scenario.jsonc stored within scenario service settings config 
'structure stored in memory
'if is_shareable present - d
'


    note over SS,SSSC #GreenYellow: **Preconditons:** \n 1.Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT 

        alt Start Up Behaviour
        VIP -> SS: NotifyIVISystemState \n (CCCM Wake Up Notification, Enum Unknown)
        SS -> SSSC: Fetch Configuration Data  
        note over SSSC : Config contains: \n client_id \n is_shareable flag
        SSSC --> SS: Return Configuration Data  
        SS -> SMC: AndroidProxy_GetStoredKeysListRequest\n(client_id = 00x)
        else Steady State
        SMC -> SS: Android_Proxy_NotifySettingDataAvailable
        SS -> SMC: AndroidProxy_GetStoredKeysListRequest\n(client_id = 00x)  
        end
        note over SMC: Sequence Flows to SMS and UCC \n are out of scope for this diagram 
        SMC -> SMC: SMC requests key_list_entry \n for Settings from SMS (QNX)
        
            alt Defined user account != AUTHENTICATED
                SMC --> SS: AndroidProxy_GetStoredKeysListResponse\n(EnumStatus =ENUM_STATUS_DATA_UNAVAILABLE)
                SS -> SS: Wait for AndroidProxy_NotifySettingsDataAvailable
            else User Account Signed In and No Custom Settings Previously Stored
                note over SS,SMC : If a User Has not Previously Configured a Custom Mood
                SMC --> SS: AndroidProxy_GetStoredKeysListResponse\n (EnumStatus =ENUM_STATUS_OK, Empty List)
                SS -> SS: <font color=red> ACTION TO BE DEFINED
            'If it's a Scenario, there's no intialisation of a value here because someone has not configured a scenario in the HMI
            else User Account Signed In and Custom Settings Previously Stored
                note over SMC : key_list_entry: \n  Scenario_CabinMoodCust1_V1 \n  Scenario_ScenarioEngineCust1_V1 \n  Scenario_ScenarioEngineCust2_V1        
                SMC --> SS: AndroidProxy_GetStoredKeysListResponse\n(EnumStatus = ENUM_STATUS_OK \n client_ID = Custom_Scenarios\n key_list_entry)
            end
        SS -> SS: Scenario Service saves key_list_entry in Volitile Memory \n (Scenario Service now has Scenario ID's \n for All Custom Scenario Settings)
    
    note over SS #GreenYellow : **USE CASE ENDS HERE**

== User Request to View Contents of Scenarios in HMI ==
    note across  #APPLICATION: **Design Methodology:** Lazy Load Design Approach where Clients are expected to request Settings upon Customer interaction with HMI to view associated Settings Values/ Data
   
    note over U,SS #GreenYellow : **Precondition:** \n 1. Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT \n 2. User Account is Signed in with Custom Settings Previously Stored

        U -> CA: User Request to View \n My Scenario's in HMI
        SS --> CA: getScenarioContentInfo \n (APP_SE, Scenario_ScenarioEngineCust1_V1)
        SS -> SMC: Android_Proxy_RecallSettingDataRequest\n(setting_name = Scenario_ScenarioEngineCust1_V1 \n Client_id = 00x) 
        
            alt Error State - Response Received Not Okay
            SMC --> SS: Android_Proxy_RecallSettingDataResponse\n(EnumStatus = ENUM_STATUS_NOT_OK) 
            SS -> SS: <font color=red> ACTION TO BE DEFINED
            'Remove this until we can confirm NOT_OKAY is a valid response
            else Steady State 
            SMC --> SS: Android_Proxy_RecallSettingDataResponse\n(EnumStatus = ENUM_STATUS_OK \n setting_value = bytes]) 
            end

        SS -> SS: settings_value interpreted within Scenario Service
        SS --> CA: ScenarioContentInfoGroup \n (ScenarioContentInfo, categoryList,statePreset,stateCustom)
        CA --> U: Display Custom Scenario 1 \n Brief Info in HMI

    note over U #GreenYellow: **USE CASE ENDS HERE**

== **User Account Switch Use Case - Removing Previous Account Data** ==

    note over U,SS #GreenYellow : **Precondition:** \n 1. Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT \n 2. User Account 1 is Signed in with Custom Settings Previously Stored 
        U-> U: User Signs Out of Account 1
        note over SMC : SMC Receives from SMS: \n Out of Scope of this Diagram
        SMC -> SS: Android_Proxy_NotifyRemoveSettingsData
        SS -> SS: Check is_shareable flag against \n each of the cached Setting_Name's
        
        alt is_shareable = false
        SS -> SS: Clear Setting from Cache
        end

        U-> U: User Signs In to Account 2
        note over SMC : SMC Receives from SMS: \n Out of Scope of this Diagram
        SMC -> SS: Android_Proxy_NotifySettingDataAvailable
    note over SS #GreenYellow: **MOVE TO STEP 6 IN CLIENT REQUEST FOR SETTINGS USE CASE**

== **Scenario deletion** ==

   note over U,SS #GreenYellow : **Precondition:** \n 1. Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT \n 2. User Account 1 is Signed in with Custom Settings Previously Stored 

        U -> CA: User Deletes Scenario
        CA -> CA: Finds Scenario ID in Volitile Memory
        note over CA : Model as "SE_C1" for Custom Scenario 1
        CA -> SS: deleteScenario(APP_SE, SE_C1)  
        SS -> SS: Maps Card ID SE_C1 to settings name \n Scenario_ScenarioEngineCust1_V1 within SMSRegistration
        SS -> SMC: DeleteSettingDataRequest(Scenario_ScenarioEngineCust1_V1,client_id = 00x)
        SMC -> SS: DeleteSettingDataResponse(EnumStatus = ENUM_STATUS_OK)
        SS -> CA: OperationResult = RET_SUCCESS
        CA -> U: Scenario Deleted in HMI

'If Delete response is NOT_OKAY - What should the HMI do? 

== ** Saving an Existing Scenario Against a User Account ** ==

U -> CA: User Requests to Save \n Existing Scenario Against User Account



== **Saving a Newly Created Custom Scenario Against a User Account** ==



@enduml