@startuml Cabin_Moods_Application_Start_Up_UC
    
title Storing and Recalling of Body System Settings      
autonumber

control "Scenario Service" as SS
database "Scenario Service Settings Config" as SSSC
participant "Settings Management Client" as SMC
participant "Vehicle Lifecycle - VIP" as VIP

== Client Request for Body Systems Settings Names == 

    note over SS,SSSC #GreenYellow: **Preconditons:** \n 1.Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT 

        alt Start Up Behaviour
        VIP -> SS: NotifyIVISystemState \n (CCCM Wake Up Notification, Enum Unknown)
        SS -> SSSC: Fetch Configuration Data  
        note over SSSC : Config contains: \n client_id \n is_shareable flag \n Setting_Name \n Personalised Settings Lookup Table
        SSSC --> SS: Return Configuration Data 
        SS -> VHAL: GetRequest against all VHAL Settings
        VHAL --> SS: GetResponse with all Body Actuator States 
        SS -> SS: Cache live value of all Body Actuator States
        SS -> SMC: Android_Proxy_RecallSettingDataRequest (Setting_Name, Client_ID) 
        else Steady State
        SMC -> SS: Android_Proxy_NotifySettingDataAvailable
        SS -> SMC: Android_Proxy_RecallSettingDataRequest (Setting_Name, Client_ID) 
        end
        note over SMC: Sequence Flows to SMS and UCC \n are out of scope for this diagram 
        SMC -> SMC: SMC requests key_list_entry \n for Settings from SMS (QNX)
        
        'Get all stored keys list 

            alt Defined user account != AUTHENTICATED
                SMC --> SS: AndroidProxy_GetStoredKeysListResponse\n(EnumStatus =ENUM_STATUS_DATA_UNAVAILABLE)
                SS -> SS: Wait for AndroidProxy_NotifySettingsDataAvailable
            else User Account Signed In and No Custom Settings Previously Stored
                note over SS,SMC : If a User Has not Previously Configured a Custom Mood
                SMC --> SS: AndroidProxy_GetStoredKeysListResponse\n (EnumStatus =ENUM_STATUS_OK, Empty List)
                ' Are we settled on ENUM_STATUS_OK as a return mechanism or want to change method 
                
                SS -> SS: Retrieve values stored from VHAL for Body Settings
                SS -> SS: Return Settings Values against ClientID
                note over  SS: Internal Lookup Table Mapping \n Setting_Name's to Android Properties
                SS -> SMC: Android_Proxy_StoreSettingDataRequest (Setting_Name, Setting_Value)
                SMC -> SMC: SMC Requests to Store Setting \n Data against SMS in QNX
                SMC --> SS: Android_Proxy_StoreSettingDataResponse (ENUM_STATUS_OK)

                    else User Account Signed In and Custom Settings Previously Stored
                    note over SMC : key_list_entry: SettingGroup_SettingName_Version
                    SMC --> SS: AndroidProxy_GetStoredKeysListResponse (EnumStatus = ENUM_STATUS_OK, client_ID = 00x, key_list_entry = SettingGroup_SettingName_Version)
                    SS -> SS: Scenario Service has list of Setting_Name's with \n Stored Settings against them
                    SS -> SMC: Android_Proxy_RecallSettingDataRequest (Setting_Name) 
                    SMC -> SMC: SMC Recalls Setting_Name data via SMS 
                    SMC -> SS: Android_Proxy_RecallSettingDataResponse (ENUM_STATUS_OK, Setting_Value)
                    SS -> SS: Scenario Service Saves Setting_Value in Volatile Memory against Setting_Name
                    SS -> SS: Lookup Table Containing Setting_Name, \n Setting_Value and Android Property
                    SS -> VHAL: Apply Personalised Body Settings against VHAL

            end
        SS -> SS: Scenario Service saves key_list_entry in Volitile Memory \n (Scenario Service now has Scenario ID's \n for All Custom Scenario Settings)

    note over SS #GreenYellow : **USE CASE ENDS HERE**


@enduml