@startuml Zero G Architecture Logic Distribution

title ZG Feature Availability Logic 

participant "User" as U
participant "CCCM Seat Application (HMI)" as SA
participant "CCCM VAL" as VAL
participant "CCCM VIP - VLC Source" as CVIP
participant "BCMB - Steering Column" as BCMB
participant "SZM - Seats" as SZM 

== Feature Availability ==

CVIP -> SA: VLCState >= Comfort 
SA -> SA: Seats Application Awake 
SA -> VAL: getZGFeatureAvailabilityRequest 

    alt Feature Not Available (Preconditions not met)
    VAL --> SA: getZGFeatureAvaiabilityResponse (EnumAvailability = NOT_AVAILABLE)
    SA -> U: Grey out ZG Button in HMI
    else Feature Available (Preconditions met)
    VAL --> SA: getZGFeatureAvaiabilityResponse (EnumAvailability = AVAILABLE)
    SA -> SA: Feature Available to Customer
    end 

== User Requests to Move to ZG Position == 

noteover SA: ZG Feature Available

U -> SA: User Input to turn ZG Feature ON 
SA -> SA: Checks values to publish against APIs for \n Steering Column and Seating
SA -> SA: Store Last Position of Steering Column 
alt Requests Published to Services in VAL
SA -> VAL: SetSteeringColumnPositionRequest (EnumSteeringColumnPosition) \n EnumSteeringColumnPosition = ENUM_FULL_UP_FULL_IN
VAL --> SA: SetSteeringColumnPositionResponse (EnumStatus)
SA -> VAL: SetSeatPositionRequest (EnumSeatPosition) \n EnumSeatPosition = ENUM_ZG_POSITION
VAL --> SA: SetSeatPositionResponse (EnumStatus)
end
VAL -> BCMB: SteerColPosnReq (Logical Value x = Full Up Full In)
VAL -> SZM: ZGPositionReq (Logical Value X = 1 ACTIVATE)
BCMB -> VAL: SteerColPosn (% Position)
SZM -> VAL: ZGPositionStatus (Logical Value X = 1 ACTIVE)

@enduml

