@startuml Rear Smart View Mirror Display Settings Personalisation

title RearDisplay Settings Load Logic

participant "User" as U
participant "SRVM \n Switch Pack" as SP
participant "CCCM \n Scenario Service" as SS
participant "Settings Management \n Service" as SMC
participant "CCCM \n VIP - VLC Source" as VIP
participant "CCCM \n VAL" as VAL
participant "BCMA" as BCMA
participant "SRVM - Mirror" as SRVM 

autonumber

== System Start Up/ Steady State ==

note over SS,VAL #GreenYellow: **START OF USE CASE**\n **Preconditons:** \n 1.Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT \n 2. SRVM Setting Set at value 1 from Cached Memory in Module/ previous drive cycle

        alt Start Up Behaviour
        VIP -> SS: NotifyIVISystemState \n (CCCM Wake Up Notification, Enum Unknown)
        SS -> VAL: GetRearViewDispBrightnessRequest()
                        VAL -> VAL: Contains latest State from \n Periodic Status signal from SRVM Module
        VAL --> SS: GetRearViewDispBrightnessResponse(EnumRearViewDispBrightness   = ENUM_REAR_VIEW_DISP_BRIGHTNESS_PRESET_1)
        SS -> SS: Cache live of Rear View Display Brightness setting (SRVM)
        SS -> SMC: Android_Proxy_RecallSettingskeys 
        note over SS,SMC: Settings Keys recall response out of scope of this diagram
        else Steady State
        SS -> SMC: Android_Proxy_RecallSettingskeys 
                note over SS,SMC: Settings Keys recall response out of scope of this diagram
        SMC -> SS: Android_Proxy_NotifySettingDataAvailable
        end

note over SS,SMC #LightBlue: Considering Happy Path Only of Authenticated Account log in with setting previously saved \n\n **Using Brightness of RearDisplay as an example**

        SS -> SS: Scenario Service has list of Setting_Name's with \n Stored Settings against them
                    SS -> SMC: Android_Proxy_RecallSettingDataRequest (RearDisplay_Brightness_Setting) 
                    SMC -> SMC: SMC Recalls \n RearDisplay_Brightness_Setting \n data via SMS 
                    SMC -> SS: Android_Proxy_RecallSettingDataResponse (ENUM_STATUS_OK, Brightness_Lvl3)
                    SS -> SS: Scenario Service Saves Brightness_Lvl3 in Volatile Memory \n against RearDisplay_Brightness_Setting
                    SS -> SS: Lookup Table Containing RearDisplay_Brightness_Setting, \n Brightness_Lvl3 and Android Property Used to Publish against API
                    SS -> VAL: SetRearViewDispBrightnessRequest (EnumRearViewDispBrightness   = ENUM_REAR_VIEW_DISP_BRIGHTNESS_PRESET_3 )
                    VAL --> SS: SetRearViewDispBrightnessResponse (ENUM_STATUS_OK)
                    VAL -> VAL: Signal to Service Mapping \n against RearDisplay Signals
                        VAL -> BCMA: SRVMBrightAdjustStep == 3
                        BCMA -> SRVM: SRVMBrightAdjustStep == 3
                        SRVM -> BCMA: SRVMBrightAdjPosRes == 3
                        BCMA -> VAL:  SRVMBrightAdjPosRes == 3
                        VAL -> SS: NotifyRearViewDispBrightness (EnumRearViewDispBrightness   = ENUM_REAR_VIEW_DISP_BRIGHTNESS_PRESET_3)
                    SS -> SS: Notify confirms users settings have been applied

note over SS,VAL #GreenYellow: **END OF USE CASE**

== User Changes Setting on Physical Switch Pack ==

note over SS,VAL #GreenYellow: **START OF USE CASE**\n **Preconditons:** \n 1.Vehicle Lifecycle State >= ENUM_VEHICLE_STATE_COMFORT \n 2. SRVM set to Brightness Level 5 based on User Profile Sign In


        U -> SP: User Request to Set \n Rear View Display \n Brightness to Level 5
                SP -> SRVM: SP Request to Set Rear View Display Brightness to Level 5
                SRVM -> SRVM: Brightness Changes to \n Brightness Level 5
                SRVM -> SRVM: LIN Module Status periodic \n and continuously reports brightness state
                        SRVM -> BCMA: SRVMBrightAdjPosRes == 5
                BCMA -> VAL:  SRVMBrightAdjPosRes == 5
                VAL -> SS: NotifyRearViewDispBrightness (EnumRearViewDispBrightness   = ENUM_REAR_VIEW_DISP_BRIGHTNESS_PRESET_5)
                SS -> SS: Scenario Service notified of value change and \n saves new value against RearDisplay_Brightness_Setting in Volitile Memory
                SS -> SS: Scenario Service stores this updated \n value against user profile via Settings Management Service
                SS -> SMC: Android_Proxy_StoreSettingDataRequest (RearDisplay_Brightness_Setting) 
                SMC -> SMC: SMC Stores \n RearDisplay_Brightness_Setting \n Value via SMS 
                SMC -> SS: Android_Proxy_StoreSettingDataResponse (ENUM_STATUS_OK, Brightness_Lvl5)

note over SS,VAL #GreenYellow: **END OF USE CASE**

@enduml