# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
# Note, An action is a pre-defined, reusable set of jobs or code that perform specific tasks within a workflow
name: GitHub Actions Software Workspace
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀                                                    
                                                      # github.actor = Property Name
                                                      # The username of the user that triggered the initial workflow run
on: [push]                                            # Workflow triggers are defined with the on key
                                                      # This example runs anytime the push event includes a file in the PlantMUL_Architecture_Sequencing directory 
                                                      # or its subdirectories, unless the file is in the PlantMUL_Architecture_Sequencing/Drafts directory.
                                                      # marches zero or more of any character
jobs:                                                 # Jobs are contained in Workflows and Run a series of Steps
   Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."