name: PlantUML_Generator
on: [push]
run-name: ${{ github.actor }} is Creating PUML Images 
jobs:                                                
  PUML_Sequence_Image_Creation:     
     runs-on: ubuntu-latest
     steps: 
        - name: Checkout
          uses: actions/checkout@v4 

        - id: plantuml
          name: PlantUML Latest Release
          run: | 
            echo "::set-output name = tag:: $(curl -s https://api.github.com/repos/plantuml/plantuml-server/releases/latest)" | grep tag_name | sed 's/.*"tag_name": "v\(.*\)",/\1/')"
         # Add description on what the call is to run here
         
        - name: "Get latest tag"
          id: current
          run: |
           echo "::set-output name=tag::$(git ls-remote --tags --refs --sort="v:refname" origin | tail -n1 | sed 's/.*\///')"

       - name: Bump docker version
          if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
          run: |
           sed -i "s#holowinski/plantuml:.*#holowinski/plantuml:${{ steps.plantuml.outputs.tag }}\"#" action.yml

      - name: Push Local Changes
         if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
         uses: ./.github/workflows/{git-auto-commit}
         with:
         ref: ${{ github.head_ref }}
         commit_message: "Bump PlantUML to ${{ steps.plantuml.outputs.tag }}"
         tagging_message: ${{ steps.plantuml.outputs.tag }}

      - name: Set up QEMU
         if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
         uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
         if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
         uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
         if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
         uses: docker/login-action@v1
         with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
         if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
         id: docker_build
         uses: docker/build-push-action@v2
         with:
         push: true
         tags: holowinski/plantuml:latest, holowinski/plantuml:${{ steps.plantuml.outputs.tag }}
         build-args: |
            PLANTUML_VERSION=${{ steps.plantuml.outputs.tag }}